// @ts-check
import js from '@eslint/js';
import { defineConfig, globalIgnores } from 'eslint/config';
import jsxA11y from 'eslint-plugin-jsx-a11y';
import reactHooks from 'eslint-plugin-react-hooks';
import globals from 'globals';
import tseslint from 'typescript-eslint';

/**
 * ESLint for the three sides of the codebase. TypeScript rules everywhere; the React hooks and
 * accessibility rules on the client only. Prettier owns formatting; function structure is checked here.
 */
export default defineConfig([
  globalIgnores([
    'dist',
    '.wrangler',
    '.worktrees',
    '.superpowers',
    'node_modules',
    'test-results',
    'playwright-report',
    'blob-report',
    // Generated by `npm run cf-typegen`.
    'worker-configuration.d.ts',
  ]),

  js.configs.recommended,
  tseslint.configs.recommended,

  {
    rules: {
      'no-restricted-syntax': [
        'error',
        {
          selector:
            'FunctionDeclaration:not(ExportNamedDeclaration > FunctionDeclaration):not(ExportDefaultDeclaration > FunctionDeclaration)',
          message: 'Use an arrow function for local helpers and handlers.',
        },
        {
          selector: 'VariableDeclarator > FunctionExpression',
          message: 'Use an arrow function for local helpers and handlers.',
        },
      ],
    },
  },

  {
    files: ['src/**/*.{ts,tsx}', 'shared/**/*.ts', 'worker/**/*.ts'],
    ignores: ['**/*.test.ts', 'worker/test/**'],
    rules: {
      'max-lines-per-function': ['error', { max: 100, skipBlankLines: true, skipComments: true }],
    },
  },

  {
    // Build, test and tooling scripts run under Node.
    files: ['*.config.{js,ts}', 'scripts/**/*.{js,mjs}', 'test/**/*.ts', 'e2e/**/*.ts'],
    languageOptions: { globals: globals.node },
  },

  {
    // Playwright fixtures destructure `{}` when they depend on no other fixture; that is the API.
    files: ['e2e/**/*.ts'],
    rules: { 'no-empty-pattern': 'off' },
  },

  {
    // The React client: browser globals, the rules of hooks and WCAG checks on the JSX.
    files: ['src/**/*.{ts,tsx}'],
    extends: [reactHooks.configs.flat.recommended, jsxA11y.flatConfigs.recommended],
    languageOptions: { globals: globals.browser },
    rules: {
      // A scrollable region needs tabIndex={0} so keyboard users can scroll it (WCAG 2.1.1); the
      // availability table relies on that, and `region` is the role such a container carries.
      'jsx-a11y/no-noninteractive-tabindex': ['error', { roles: ['tabpanel', 'region'] }],
    },
  },
]);
